upstream/django-scratchpad/scratchpad/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from django.contrib.auth import views as auth_views

urlpatterns = patterns('',
    url(r'^list/$', 'scratchpad.views.view_list',name='scratchpad-list'),
    url(r'^$', 'scratchpad.views.view_list',name='scratchpad-list-index'),
    url(r'^new/$', 'scratchpad.views.new_scratchpad',name="scratchpad-new"),
    url(r'^(?P<scratch_id>\d+)/$', 'scratchpad.views.scratchpad',name="scratchpad-scratchpad_view"),
    url(r'^(?P<scratch_id>\d+)/del$', 'scratchpad.views.scratchpad_del',name="scratchpad-delete"),
    url(r'^add/$', 'scratchpad.views.add_to',name="scratchpad-addto"),
    url(r'^add/save/$', 'scratchpad.views.save',name="scratchpad-save"),
    url(r'^item/(?P<item_id>\d+)/$', 'scratchpad.views.item', name="scratchpad-item"),
    url(r'^item/(?P<item_id>\d+)/del$', 'scratchpad.views.del_item',name="scratchpad-item-delete"),
    url(r'^not_available/$', direct_to_template, dict(template='not_available.html'), name="scratchpad-not-available"),




    url(r'^test/$','scratchpad.views.test')
)

upstream/django-scratchpad/scratchpad/models.py
from django.db import models
from django.contrib.auth.models import User,Group
from muaccounts  import models as muamodels
from todo import models as todomodels
# Create your models here.


class Scratchpad(models.Model):
    title = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User)
    account = models.ForeignKey(muamodels.MUAccount)
    tasks_list = models.ForeignKey(todomodels.List, null=True, blank=True)

    def __unicode__(self):
        return self.title


    class Meta:
        unique_together = ("account", "title")


class Item(models.Model):
    scratchpad = models.ForeignKey(Scratchpad)
    title = models.CharField(max_length=200)
    notes = models.TextField()
    createddate = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User)

    def __unicode__(self):
        return self.title


class ItemComment(models.Model):
    item = models.ForeignKey(Item)
    author = models.ForeignKey(User)
    text = models.TextField()
    parent = models.ForeignKey("ItemComment",null=True,default=None)

    def __unicode__(self):
        return "%s: %s" % (self.author, self.text)

upstream/django-scratchpad/scratchpad/templates/addto_scratchpad.html
{% extends "main.html" %}

{% block body %}

<h1>Add to Scratchpad</h1>
	<form action="{% url scratchpad-save %}" method="POST" id="addto_scratchpad">
	<table>
	<tr><th><label for="scratch_content">Content:</label></th>
	<td id="scratch_content">&nbsp;</td></tr>


	<tr><th colspan="2"><label for="">

	<a href="#" onclick="selscratchpad(2); return false;">Select scratchpad</a>
	|
	<a href="#" onclick="selscratchpad(1); return false;">New Scratchpad</a>
	</label>
	<script>
	function selscratchpad(t)
	{
		if(t == 1)
		{
			document.getElementById("new_scratchpad").style.display = "";
			document.getElementById("id_scratchpad").parentNode.parentNode.style.display = "none";
			document.getElementById("scratchpad_type").value = "new";
		}
		else
		{

			document.getElementById("new_scratchpad").style.display = "none";
			document.getElementById("id_scratchpad").parentNode.parentNode.style.display = "";
			document.getElementById("scratchpad_type").value = "select";
		}
	}
	</script>
	<input type="hidden" id="scratchpad_type" name="scratchpad_type" value="select">
	</th>
	</tr>

	<tr id="new_scratchpad" style="display:none"><th><label for="">Scratchpad:</label></th>
	<td id=""><input type="text" name="new_scratchpad"></td></tr>

	{{ form }}
	<tr>
	<th><label for="comment_id">Comment:</label></th>
	<td>{{ comment }} </td></tr>
	</table>
	<p><input type="submit" value="Submit" class="todo-button"></p>
	<script>
	data = document.getElementById("addto_scratchpad").notes.value;
	document.getElementById("scratch_content").innerHTML = data;

	data = document.getElementById("addto_scratchpad").notes.value;

	</script>
	</form>
{% endblock %}

upstream/django-scratchpad/scratchpad/templates/confirmdel_scratchpad.html
{% extends "main.html" %}

{% block body %}

<h1>Confirm deletion of Scratchpad "{{pad}}"</h1>
<h2>This will delete all it's notes and comments.<br>The action is permanent and can't be undone.</h2>
<form method="post" action="{% url scratchpad-delete pad.id %}">
<input type="button" name="cancel" value="Cancel" onclick="document.location.href='{% url scratchpad-scratchpad_view pad.id %}'";>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="submit" name="del" value="Delete">
</form>


{% endblock %}

upstream/django-scratchpad/scratchpad/templates/confirmdel_scratchpad_item.html
{% extends "main.html" %}

{% block body %}

<h1>Confirm deletion of item "{{item}}"</h1>
<h2>This will delete all it's comments.<br>The action is permanent and can't be undone.</h2>
<form method="post" action="{% url scratchpad-item-delete item.id %}">
<input type="button" name="cancel" value="Cancel" onclick="document.location.href='{% url scratchpad-scratchpad_view item.scratchpad.id %}'";>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="submit" name="del" value="Delete">
</form>


{% endblock %}

upstream/django-scratchpad/scratchpad/templates/list_scratchpads.html
{% extends "main.html" %}

{% block body %}

<h1>Your Scratchpads</h1>

<ul>
{% for pad in pads %}
<li><a href="{% url scratchpad-scratchpad_view pad.id %}">{{pad.title}}</a></li>
{% endfor %}
</ul>

<h1>New Scratchpad</h1>
	<form action="{% url scratchpad-new %}" method="POST">
	<table>{{ form }}</table>
	<p><input type="submit" value="Submit" class="todo-button"></p>
	</form>

{% endblock %}

upstream/django-scratchpad/scratchpad/templates/new_scratchpad.html
{% extends "main.html" %}

{% block body %}

<h1>New Scratchpad</h1>
	<form action="." method="POST">
	<table>{{ form }}</table>
	<p><input type="submit" value="Submit" class="todo-button"></p>
	</form>
{% endblock %}

upstream/django-scratchpad/scratchpad/templates/not_available.html
{% extends "main.html" %}

{% block title %}Not available{% endblock %}

{% block body %}
<h1>Scratchpad not available</h1>
<p>You don't have Scratchpad activated for you plan.</p>
{% endblock %}

upstream/django-scratchpad/scratchpad/templates/test.html
{% extends "main.html" %}
{% block head %}
<style>

.scratchpad
{
border-style: solid;
border-size:1px;
border-color:#000000;
margin: 2px;
}
</style>

<script>
function addToScratchpad(id)
{
	obj = document.getElementById(id);
	frm = document.getElementById("scratchpad_add_"+id);
	frm.data.value = obj.innerHTML;
	frm.submit();

}
</script>
{% endblock %}
{% block body %}

<h1>TEST</h1>

{% load scratchpad_tags  %}



<div id="test_1" class="scratchpad">
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec id nulla sem. Proin molestie nibh a ipsum adipiscing pulvinar. Sed ac ligula in nisl vehicula ornare. Vivamus a vulputate libero. Duis est magna, convallis ac iaculis non, vestibulum non diam. Mauris nec orci ac lacus ultricies lobortis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aenean elit odio, elementum in mollis quis, rhoncus id quam. Vivamus augue tortor, interdum sit amet porta nec, volutpat eget lacus. Pellentesque at dictum urna. Mauris adipiscing nisi eget augue porta luctus. Donec nec dui id massa vulputate varius. Sed ac tempus nibh. Proin ornare laoreet sagittis.
</div>
{% get_add_to_html 'test_1' %}

<div id="test_2" class="scratchpad">
Curabitur iaculis nulla at mauris tempus tristique. Sed luctus sem elementum leo tempor aliquet. Vestibulum a rhoncus tellus. Nam lobortis libero sapien. Pellentesque faucibus tortor vitae sapien pellentesque vel eleifend neque egestas. Nullam egestas venenatis tristique. Vivamus ante diam, dignissim vitae laoreet et, volutpat eu ante. Aliquam dapibus turpis vitae eros gravida ultrices. Cras gravida placerat justo. Duis risus dui, bibendum rutrum feugiat sed, venenatis non arcu. Maecenas eu neque sed nulla ultrices porttitor. Suspendisse sit amet purus nec elit ultrices aliquet sed eu magna. Sed vulputate nisi id nibh consectetur auctor. Ut commodo, nibh aliquam laoreet ullamcorper, nulla ipsum dignissim metus, eu feugiat turpis nisi a nunc. Aenean mi massa, venenatis vel blandit ac, scelerisque sed elit. Pellentesque aliquet placerat leo, at ornare erat faucibus id. Proin in arcu mi. Phasellus gravida ligula nec sem iaculis ac lacinia diam placerat. Quisque vitae magna vel ipsum ullamcorper bibendum a et massa. Cras nec dignissim felis.
</div>
{% get_add_to_html 'test_2' %}

<div id="test_3" class="scratchpad">
In hac habitasse platea dictumst. Nulla pellentesque rhoncus quam non malesuada. Maecenas faucibus ligula ut tellus vulputate interdum. Integer et ligula quis nibh cursus sodales. Integer ac neque ut dui semper imperdiet. Donec lacinia ante ut tortor sodales varius tempus nulla venenatis. Aliquam non ante eu orci tincidunt pulvinar. Curabitur sagittis consectetur rhoncus. Quisque vel nulla non orci feugiat sodales. Suspendisse quam eros, malesuada eget euismod vel, sagittis at purus. Proin vel tempus lorem. Etiam ut turpis tristique dui scelerisque interdum a a odio. Cras malesuada nisl sit amet tellus vestibulum nec porta tortor luctus. In nec magna metus, ut ultrices ante. Curabitur mollis commodo vehicula. In fringilla quam in ipsum convallis consectetur. Curabitur adipiscing mauris faucibus tellus dapibus ut scelerisque neque cursus.
</div>
{% get_add_to_html 'test_3' %}

<div id="test_4" class="scratchpad">
<img src="http://www.google.com/intl/en_ALL/images/logo.gif">
</div>
{% get_add_to_html 'test_4' %}

<div id="test_5" class="scratchpad">
Oembed link: http://www.flickr.com/photos/bees/2341623661/
</div>
{% get_add_to_html 'test_5' %}




{% endblock %}

upstream/django-scratchpad/scratchpad/templates/view_scratchpad.html
{% extends "main.html" %}
{% load threadedcommentstags %}
{% load oembed_tags %}


{% block head %}
<script type="text/javascript">
function show_reply_form(comment_id, url, person_name) {
    var comment_reply = $('#' + comment_id);
    var to_add = $( new Array(
    '<div class="response"><p>Reply to ' + person_name + ':</p>',
    '<form method="POST" action="' + url + '">',
    {% get_threaded_comment_form as form %}
    '<ul>',  '{{ form.as_ul|oneline }}',
    '<li><input type="submit" value="Submit Comment" /></li>',
    '</ul>', '</form>', '</div>').join(''));
    to_add.css("display", "none");
    comment_reply.after(to_add);
    to_add.slideDown(function() {
        comment_reply.replaceWith(new Array('<a id="',
        comment_id,'" href="javascript:hide_reply_form(\'',
        comment_id, '\',\'', url, '\',\'', person_name,
        '\')">Stop Replying</a>').join(''));
    });
}
function hide_reply_form(comment_id, url, person_name) {
    var comment_reply = $('#' + comment_id);
    comment_reply.next().slideUp(function (){
        comment_reply.next('.response').remove();
        comment_reply.replaceWith(new Array('<a id="',
        comment_id,'" href="javascript:show_reply_form(\'',
        comment_id, '\',\'', url, '\',\'', person_name,
        '\')">Reply</a>').join(''));
    });
}
</script>
{% endblock %}
{% block body %}

<h1>Scratchpad: {{pad}}</h1>
{% ifequal pad.author request.user %}
<a href="{% url scratchpad-delete pad.id %}">Delete this scratchpad</a><br>
{% endifequal %}
<a href="{% url scratchpad-list%}">View scratchpads list</a>
<hr>
{% if pad.tasks_list %}
<a href="{% url todo-incomplete_tasks pad.tasks_list.id pad.tasks_list.slug %}">View scratchpad tasks</a>
<hr>
{% endif %}

{% for item in pad.item_set.all %}

<h3><a href="{% url scratchpad-item item.id %}">{{ item }}</a></h3>

{% autoescape off %}
<div>{% oembed %}{{item.notes}}{% endoembed %}</div>
{% endautoescape %}

{% ifequal pad.author request.user %}
{% get_comment_count for item as item_comments %} Comments: {{ item_comments }}
<br>
<a href="{% url scratchpad-item-delete item.id %}">Delete item</a>
{% endifequal %}
<hr>

{% endfor %}
<hr>
{% if pad.tasks_list %}
<a href="{% url todo-incomplete_tasks pad.tasks_list.id pad.tasks_list.slug %}">View scratchpad tasks</a>
{% else %}
<a href="{% url todo-not-available %}">View scratchpad tasks</a>
{% endif %}

    <h3>Comments on This Scratchpad:</h3>
    {% get_threaded_comment_tree for pad as tree %}
    {% for comment in tree %}
        <div style="margin-left: {{ comment.depth }}em;" class="comment">
            {{ comment.user }} said:<br/>
            {% auto_transform_markup comment %}
        </div>
		<a id="c{{ comment.id }}" href="javascript:show_reply_form('c{{ comment.id }}','{% get_comment_url pad comment %}','{{ comment.user }}')">Reply</a>

    {% endfor %}
    <p>Reply to Original:</p>
    <form method="POST" action="{% get_comment_url pad %}">
        <ul>
        {% get_threaded_comment_form as form %}
            {{ form.as_ul }}
            <li><input type="submit" value="Submit Comment" /></li>
        </ul>
    </form>

{% endblock %}

upstream/django-scratchpad/scratchpad/templates/view_scratchpad_item.html
{% extends "main.html" %}

{% load threadedcommentstags %}



{% block head %}
<script type="text/javascript">
function show_reply_form(comment_id, url, person_name) {
    var comment_reply = $('#' + comment_id);
    var to_add = $( new Array(
    '<div class="response"><p>Reply to ' + person_name + ':</p>',
    '<form method="POST" action="' + url + '">',
    {% get_threaded_comment_form as form %}
    '<ul>',  '{{ form.as_ul|oneline }}',
    '<li><input type="submit" value="Submit Comment" /></li>',
    '</ul>', '</form>', '</div>').join(''));
    to_add.css("display", "none");
    comment_reply.after(to_add);
    to_add.slideDown(function() {
        comment_reply.replaceWith(new Array('<a id="',
        comment_id,'" href="javascript:hide_reply_form(\'',
        comment_id, '\',\'', url, '\',\'', person_name,
        '\')">Stop Replying</a>').join(''));
    });
}
function hide_reply_form(comment_id, url, person_name) {
    var comment_reply = $('#' + comment_id);
    comment_reply.next().slideUp(function (){
        comment_reply.next('.response').remove();
        comment_reply.replaceWith(new Array('<a id="',
        comment_id,'" href="javascript:show_reply_form(\'',
        comment_id, '\',\'', url, '\',\'', person_name,
        '\')">Reply</a>').join(''));
    });
}
</script>
{% endblock %}

{% block body %}


<h1>Scratchpad: <a href="{% url scratchpad-scratchpad_view item.scratchpad.id%}">{{item.scratchpad}}</a></h1>
<h2>Item: {{item}}</h2>

<a href="{% url todo-incomplete_tasks item.scratchpad.tasks_list.id item.scratchpad.tasks_list.slug %}">View tasks</a>

{% autoescape off %}
<div>{{item.notes}}</div>
{% endautoescape %}

<a href="{% url todo-incomplete_tasks item.scratchpad.tasks_list.id item.scratchpad.tasks_list.slug %}">View tasks</a>

{% for item in pad.item_set.all %}
<h3><a href="{% url scratchpad-item item.id%}">{{ item }}</a></h3>
{% autoescape off %}
<div>{{item.notes}}</div>
{% endautoescape %}
<hr>

{% endfor %}

    <h3>Comments on This Item:</h3>
    {% get_threaded_comment_tree for item as tree %}
    {% for comment in tree %}
        <div style="margin-left: {{ comment.depth }}em;" class="comment">
            {{ comment.user }} said:<br/>
            {% auto_transform_markup comment %}
        </div>
		<a id="c{{ comment.id }}" href="javascript:show_reply_form('c{{ comment.id }}','{% get_comment_url item comment %}','{{ comment.name }}')">Reply</a>

    {% endfor %}
    <p>Reply to Original:</p>
    <form method="POST" action="{% get_comment_url item %}">
        <ul>
        {% get_threaded_comment_form as form %}
            {{ form.as_ul }}
            <li><input type="submit" value="Submit Comment" /></li>
        </ul>
    </form>

{% endblock %}